# Domain: Order
# Path: Test:Order
# Generated by ontology-lift with FIBO enrichment
# FIBO Coverage: 88.9%

# Concepts
Buy: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: inherited (confidence: 0.70)
  # Extends: Order
Custody fee: A contract between an investor and a custodian bank for the safekeeping of securities and other assets.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesHoldings/CustodyAgreement
  # Match: keyword (confidence: 0.73)
  # Extends: Custody Agreement
Digital Onboarding Channel: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: parent (confidence: 0.80)
  # Extends: Order
Executed order: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: keyword (confidence: 0.84)
  # Extends: Order
Monthly: total monthly qualifying income of a potential borrower
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/LOAN/LoansGeneral/LoanApplications/BorrowerMonthlyIncome
  # Match: keyword (confidence: 0.68)
  # Extends: borrower monthly income
Non-digital Onboarding Channel: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: parent (confidence: 0.80)
  # Extends: Order
One-time: enumeration that indicates whether a calendar-specified date is figured from the start or the end of a calendar period
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FND/DatesAndTimes/FinancialDates/TimeDirection
  # Match: keyword (confidence: 0.74)
  # Extends: time direction
Order: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: exact (confidence: 1.00)
  # Extends: Order
Payment: delivery of money in fulfillment of an obligation, such as to satisfy a claim or debt
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/PaymentsAndSchedules/Payment
  # Match: exact (confidence: 1.00)
  # Extends: payment
Placed order: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: keyword (confidence: 0.84)
  # Extends: Order
Position: investor's stake, i.e., a holding, in a particular asset (such as an individual security)
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Position
  # Match: exact (confidence: 1.00)
  # Extends: position
Sales: exchange of goods or services for money
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FND/ProductsAndServices/ProductsAndServices/Sale
  # Match: fuzzy (confidence: 0.80)
  # Extends: sale
Saving plan (regular investment): banking institution organized to accept savings deposits and pay interest on those savings deposits
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntities/SavingsBank
  # Match: keyword (confidence: 0.74)
  # Extends: savings bank
Sell: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: parent (confidence: 0.80)
  # Extends: Order
SellAction: Schema.org concept: https://schema.org/SellAction
  # Source: EXPLICIT (confidence: EXPLICIT)
  # Extends: Thing
Service Channel: Schema.org concept: https://schema.org/ServiceChannel
  # Source: EXPLICIT (confidence: EXPLICIT)
  # Extends: Thing
Settled order: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: keyword (confidence: 0.84)
  # Extends: Order
Weekly: measure of the average weekly wage an employee makes over the reporting period
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/IND/EconomicIndicators/EconomicIndicators/AverageWeeklyEarnings
  # Match: keyword (confidence: 0.68)
  # Extends: average weekly earnings

# Categorizations
Order =< @ by [Onboarding Channel] >= [Non-digital Onboarding Channel, Digital Onboarding Channel]
Order =< @ by state >= [Executed order, Settled order, Placed order]
Order =< @ by the frequency of trading >= [Saving plan (regular investment), One-time]
Order =< @ by the kind of trading >= [Sell, Buy]
Saving plan (regular investment) =< @ by the frequency >= [Weekly, Monthly]
