#!/bin/bash
#
# BKB Explorer - Data Preparation Script
#
# Copies ontology data from ontology-lift/export and bundles it
# into js/data.js for offline use.
#
# Usage: ./prepare-demo.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/js/data.js"
ONTOLOGY_LIFT_DIR="$SCRIPT_DIR/../ontology-lift"

echo "🏦 BKB Explorer - Preparing demo data..."
echo ""

# Check if ontology-lift exists
if [ ! -d "$ONTOLOGY_LIFT_DIR" ]; then
    echo "❌ Error: ontology-lift directory not found at $ONTOLOGY_LIFT_DIR"
    exit 1
fi

# Find export directories
EXPORT_DIR="$ONTOLOGY_LIFT_DIR/export"
if [ ! -d "$EXPORT_DIR" ]; then
    # Try demo output
    EXPORT_DIR="$ONTOLOGY_LIFT_DIR/demo/output/cross-domain"
fi

if [ ! -d "$EXPORT_DIR" ]; then
    echo "❌ Error: No export directory found. Run ontology-lift pipeline first."
    exit 1
fi

echo "📂 Using export directory: $EXPORT_DIR"
echo ""

# Find ontology.json files
INVESTMENT_FILE=$(find "$EXPORT_DIR" -path "*Investment*" -name "ontology.json" | head -1)
PAYMENTS_FILE=$(find "$EXPORT_DIR" -path "*Payment*" -name "ontology.json" | head -1)
RETAIL_FILE=$(find "$EXPORT_DIR" -path "*Retail*" -name "ontology.json" 2>/dev/null | head -1)

# Generate data.js
echo "📝 Generating $OUTPUT_FILE..."
echo ""

cat > "$OUTPUT_FILE" << 'HEADER'
/**
 * BKB Explorer - Data
 *
 * Auto-generated by prepare-demo.sh
 * DO NOT EDIT MANUALLY
 *
HEADER

echo " * Generated: $(date)" >> "$OUTPUT_FILE"
echo " */" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Domains index
echo "// Domain hierarchy" >> "$OUTPUT_FILE"
echo "const DOMAINS_DATA = {" >> "$OUTPUT_FILE"
echo '  "version": "1.0",' >> "$OUTPUT_FILE"
echo "  \"generated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"," >> "$OUTPUT_FILE"
echo '  "hierarchy": {' >> "$OUTPUT_FILE"
echo '    "RBCZ": {' >> "$OUTPUT_FILE"
echo '      "type": "enterprise",' >> "$OUTPUT_FILE"
echo '      "children": {' >> "$OUTPUT_FILE"
echo '        "MIB": {' >> "$OUTPUT_FILE"
echo '          "type": "business_unit",' >> "$OUTPUT_FILE"
echo '          "children": {' >> "$OUTPUT_FILE"

# Count concepts
INV_COUNT=0
PAY_COUNT=0
RET_COUNT=0

if [ -f "$INVESTMENT_FILE" ]; then
    INV_COUNT=$(python3 -c "import json; print(len(json.load(open('$INVESTMENT_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi
if [ -f "$PAYMENTS_FILE" ]; then
    PAY_COUNT=$(python3 -c "import json; print(len(json.load(open('$PAYMENTS_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi
if [ -f "$RETAIL_FILE" ]; then
    RET_COUNT=$(python3 -c "import json; print(len(json.load(open('$RETAIL_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi

echo "            \"Investment\": { \"type\": \"domain\", \"stats\": { \"concepts\": $INV_COUNT } }," >> "$OUTPUT_FILE"
echo "            \"Payments\": { \"type\": \"domain\", \"stats\": { \"concepts\": $PAY_COUNT } }" >> "$OUTPUT_FILE"
echo '          }' >> "$OUTPUT_FILE"
echo '        },' >> "$OUTPUT_FILE"
echo "        \"Retail\": { \"type\": \"domain\", \"stats\": { \"concepts\": $RET_COUNT } }" >> "$OUTPUT_FILE"
echo '      }' >> "$OUTPUT_FILE"
echo '    }' >> "$OUTPUT_FILE"
echo '  },' >> "$OUTPUT_FILE"

# Cross-domain detection
echo '  "crossDomain": {' >> "$OUTPUT_FILE"
if [ -f "$INVESTMENT_FILE" ] && [ -f "$PAYMENTS_FILE" ]; then
    python3 << PYTHON >> "$OUTPUT_FILE"
import json

inv = json.load(open('$INVESTMENT_FILE'))
pay = json.load(open('$PAYMENTS_FILE'))

inv_names = {c['name'] for c in inv.get('concepts', [])}
pay_names = {c['name'] for c in pay.get('concepts', [])}

shared = inv_names & pay_names

entries = []
for name in sorted(shared):
    inv_concept = next((c for c in inv['concepts'] if c['name'] == name), None)
    fibo_uri = None
    if inv_concept and inv_concept.get('fibo_mapping'):
        fibo_uri = inv_concept['fibo_mapping'].get('uri')

    domains = ["Investment", "Payments"]
    entry = f'    "{name}": {{ "domains": {json.dumps(domains)}'
    if fibo_uri:
        entry += f', "fibo_uri": "{fibo_uri}"'
    entry += ' }'
    entries.append(entry)

print(',\n'.join(entries))
PYTHON
fi
echo '  }' >> "$OUTPUT_FILE"
echo '};' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Investment data
echo "// Investment domain" >> "$OUTPUT_FILE"
echo -n "const INVESTMENT_DATA = " >> "$OUTPUT_FILE"
if [ -f "$INVESTMENT_FILE" ]; then
    cat "$INVESTMENT_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Investment: $INV_COUNT concepts"
else
    echo '{ "domain": { "name": "Investment", "path": "RBCZ:MIB:Investment" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Investment: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Payments data
echo "// Payments domain" >> "$OUTPUT_FILE"
echo -n "const PAYMENTS_DATA = " >> "$OUTPUT_FILE"
if [ -f "$PAYMENTS_FILE" ]; then
    cat "$PAYMENTS_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Payments: $PAY_COUNT concepts"
else
    echo '{ "domain": { "name": "Payments", "path": "RBCZ:MIB:Payments" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Payments: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Retail data
echo "// Retail domain" >> "$OUTPUT_FILE"
echo -n "const RETAIL_DATA = " >> "$OUTPUT_FILE"
if [ -f "$RETAIL_FILE" ]; then
    cat "$RETAIL_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Retail: $RET_COUNT concepts"
else
    echo '{ "domain": { "name": "Retail", "path": "RBCZ:Retail" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Retail: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Export
echo "// Export for application" >> "$OUTPUT_FILE"
echo "window.BKB_DATA = {" >> "$OUTPUT_FILE"
echo "  domains: DOMAINS_DATA," >> "$OUTPUT_FILE"
echo "  investment: INVESTMENT_DATA," >> "$OUTPUT_FILE"
echo "  payments: PAYMENTS_DATA," >> "$OUTPUT_FILE"
echo "  retail: RETAIL_DATA" >> "$OUTPUT_FILE"
echo "};" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "console.log('✅ BKB data loaded:', Object.keys(window.BKB_DATA));" >> "$OUTPUT_FILE"

# Report
FILE_SIZE=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
FILE_SIZE_KB=$((FILE_SIZE / 1024))
echo ""
echo "✅ Generated $OUTPUT_FILE"
echo "   Size: ${FILE_SIZE_KB} KB"
echo ""
echo "🚀 Ready! Open index.html in browser."
