#!/bin/bash
#
# BKB Explorer - Test Demo Preparation Script (ADR-029)
#
# Copies test data from conceptspeak/tests (Single Source of Truth),
# runs the pipeline, and generates js/data.js for visualization.
#
# Usage: ./prepare-test-demo.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONCEPTSPEAK_DIR="$SCRIPT_DIR/../conceptspeak"
DOMAIN_FORGE_DIR="$SCRIPT_DIR/../domain-forge"
ONTOLOGY_LIFT_DIR="$SCRIPT_DIR/../ontology-lift"
OUTPUT_FILE="$SCRIPT_DIR/js/data.js"

echo "BKB Explorer - Preparing test demo data..."
echo ""

# Check dependencies
if [ ! -d "$CONCEPTSPEAK_DIR/tests" ]; then
    echo "Error: conceptspeak/tests not found at $CONCEPTSPEAK_DIR/tests"
    exit 1
fi

if [ ! -d "$DOMAIN_FORGE_DIR" ]; then
    echo "Error: domain-forge not found at $DOMAIN_FORGE_DIR"
    exit 1
fi

if [ ! -d "$ONTOLOGY_LIFT_DIR" ]; then
    echo "Error: ontology-lift not found at $ONTOLOGY_LIFT_DIR"
    exit 1
fi

# Create test directories
mkdir -p "$SCRIPT_DIR/test/Order"
mkdir -p "$SCRIPT_DIR/test/Position"
mkdir -p "$SCRIPT_DIR/test/Transaction"

echo "Step 1: Copying test data from conceptspeak/tests..."

# Copy test files (Single Source of Truth)
cp "$CONCEPTSPEAK_DIR/tests/Investment_Order.test" "$SCRIPT_DIR/test/Order/Investment_Order.cs"
cp "$CONCEPTSPEAK_DIR/tests/InvestmentPosition.test" "$SCRIPT_DIR/test/Position/Investment_Position.cs"
cp "$CONCEPTSPEAK_DIR/tests/Investment_Transaction.test" "$SCRIPT_DIR/test/Transaction/Investment_Transaction.cs"

echo "  - Order/Investment_Order.cs"
echo "  - Position/Investment_Position.cs"
echo "  - Transaction/Investment_Transaction.cs"
echo ""

# Create config files
cat > "$SCRIPT_DIR/test/Order/config.json" << 'EOF'
{
  "domain": {
    "path": "Test:Order",
    "name": "Order"
  },
  "sources": [
    "Investment_Order.cs"
  ]
}
EOF

cat > "$SCRIPT_DIR/test/Position/config.json" << 'EOF'
{
  "domain": {
    "path": "Test:Position",
    "name": "Position"
  },
  "sources": [
    "Investment_Position.cs"
  ]
}
EOF

cat > "$SCRIPT_DIR/test/Transaction/config.json" << 'EOF'
{
  "domain": {
    "path": "Test:Transaction",
    "name": "Transaction"
  },
  "sources": [
    "Investment_Transaction.cs"
  ]
}
EOF

echo "Step 2: Running domain-forge..."

# Run domain-forge
cd "$DOMAIN_FORGE_DIR"
python -m domain_forge consolidate "$SCRIPT_DIR/test/Order/config.json"
python -m domain_forge consolidate "$SCRIPT_DIR/test/Position/config.json"
python -m domain_forge consolidate "$SCRIPT_DIR/test/Transaction/config.json"
echo ""

echo "Step 3: Running ontology-lift..."

# Run ontology-lift
cd "$ONTOLOGY_LIFT_DIR"
python -m ontology_lift.cli lift "$SCRIPT_DIR/test/Order/domain.json" -o "$SCRIPT_DIR/test/Order/"
python -m ontology_lift.cli lift "$SCRIPT_DIR/test/Position/domain.json" -o "$SCRIPT_DIR/test/Position/"
python -m ontology_lift.cli lift "$SCRIPT_DIR/test/Transaction/domain.json" -o "$SCRIPT_DIR/test/Transaction/"
echo ""

echo "Step 4: Generating data.js..."

# Generate data.js
ORDER_FILE="$SCRIPT_DIR/test/Order/Test:Order/ontology.json"
POSITION_FILE="$SCRIPT_DIR/test/Position/Test:Position/ontology.json"
TRANSACTION_FILE="$SCRIPT_DIR/test/Transaction/Test:Transaction/ontology.json"

python3 << PYTHON
import json
from datetime import datetime

# Load ontologies
with open('$ORDER_FILE') as f:
    order_data = json.load(f)

with open('$POSITION_FILE') as f:
    position_data = json.load(f)

with open('$TRANSACTION_FILE') as f:
    transaction_data = json.load(f)

# Generate data.js
output = f'''/**
 * BKB Explorer - Test Demo Data
 *
 * Auto-generated by prepare-test-demo.sh (ADR-029)
 * Source: conceptspeak/tests/
 * DO NOT EDIT MANUALLY
 *
 * Generated: {datetime.now().isoformat()}
 */

// Domain hierarchy
const DOMAINS_DATA = {{
  "version": "1.0",
  "hierarchy": {{
    "Test": {{
      "type": "test",
      "children": {{
        "Order": {{ "type": "domain", "stats": {{ "concepts": {len(order_data['concepts'])} }} }},
        "Position": {{ "type": "domain", "stats": {{ "concepts": {len(position_data['concepts'])} }} }},
        "Transaction": {{ "type": "domain", "stats": {{ "concepts": {len(transaction_data['concepts'])} }} }}
      }}
    }}
  }},
  "crossDomain": {{}}
}};

// Order domain
const ORDER_DATA = {json.dumps(order_data, indent=2)};

// Position domain
const POSITION_DATA = {json.dumps(position_data, indent=2)};

// Transaction domain
const TRANSACTION_DATA = {json.dumps(transaction_data, indent=2)};

// Export for application
window.BKB_DATA = {{
  domains: DOMAINS_DATA,
  order: ORDER_DATA,
  position: POSITION_DATA,
  transaction: TRANSACTION_DATA
}};

console.log('BKB Test data loaded:', Object.keys(window.BKB_DATA));
'''

with open('$OUTPUT_FILE', 'w') as f:
    f.write(output)

print(f"  Order: {len(order_data['concepts'])} concepts")
print(f"  Position: {len(position_data['concepts'])} concepts")
print(f"  Transaction: {len(transaction_data['concepts'])} concepts")
PYTHON

echo ""
echo "Done!"
echo ""
echo "Generated: $OUTPUT_FILE"
echo ""
echo "Open index.html in browser to view the demo."
