#!/bin/bash
#
# BKB Explorer - Public Data Preparation Script
#
# Generates js/data.js with TEST DATA ONLY (no RBCZ production data).
# Safe for public GitHub repository.
#
# Usage: ./prepare-public.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/js/data.js"

echo "🔓 BKB Explorer - Preparing PUBLIC demo data (Test only)..."
echo ""

# Find Test ontology.json files
TEST_ORDER_FILE="$SCRIPT_DIR/test/Order/Test:Order/ontology.json"
TEST_POSITION_FILE="$SCRIPT_DIR/test/Position/Test:Position/ontology.json"
TEST_TRANSACTION_FILE="$SCRIPT_DIR/test/Transaction/Test:Transaction/ontology.json"
TEST_PAYMENT_FILE="$SCRIPT_DIR/test/Payment/Test:Payment/ontology.json"

# Run test demo first to ensure test data exists
if [ ! -f "$TEST_ORDER_FILE" ]; then
    echo "📦 Generating test data..."
    "$SCRIPT_DIR/prepare-test-demo.sh" > /dev/null 2>&1 || true
fi

# Generate data.js
echo "📝 Generating $OUTPUT_FILE..."
echo ""

cat > "$OUTPUT_FILE" << 'HEADER'
/**
 * BKB Explorer - Data (PUBLIC VERSION)
 *
 * Auto-generated by prepare-public.sh
 * Contains TEST DATA ONLY - safe for public repository
 *
HEADER

echo " * Generated: $(date)" >> "$OUTPUT_FILE"
echo " */" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Count Test concepts
TEST_ORDER_COUNT=0
TEST_POSITION_COUNT=0
TEST_TRANSACTION_COUNT=0
TEST_PAYMENT_COUNT=0

if [ -f "$TEST_ORDER_FILE" ]; then
    TEST_ORDER_COUNT=$(python3 -c "import json; print(len(json.load(open('$TEST_ORDER_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi
if [ -f "$TEST_POSITION_FILE" ]; then
    TEST_POSITION_COUNT=$(python3 -c "import json; print(len(json.load(open('$TEST_POSITION_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi
if [ -f "$TEST_TRANSACTION_FILE" ]; then
    TEST_TRANSACTION_COUNT=$(python3 -c "import json; print(len(json.load(open('$TEST_TRANSACTION_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi
if [ -f "$TEST_PAYMENT_FILE" ]; then
    TEST_PAYMENT_COUNT=$(python3 -c "import json; print(len(json.load(open('$TEST_PAYMENT_FILE'))['concepts']))" 2>/dev/null || echo 0)
fi

# Domains index (Test only)
echo "// Domain hierarchy (TEST DATA ONLY)" >> "$OUTPUT_FILE"
echo "const DOMAINS_DATA = {" >> "$OUTPUT_FILE"
echo '  "version": "1.0-public",' >> "$OUTPUT_FILE"
echo "  \"generated\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"," >> "$OUTPUT_FILE"
echo '  "hierarchy": {' >> "$OUTPUT_FILE"
echo '    "Test": {' >> "$OUTPUT_FILE"
echo '      "type": "test",' >> "$OUTPUT_FILE"
echo '      "children": {' >> "$OUTPUT_FILE"
echo "        \"Order\": { \"type\": \"domain\", \"stats\": { \"concepts\": $TEST_ORDER_COUNT } }," >> "$OUTPUT_FILE"
echo "        \"Position\": { \"type\": \"domain\", \"stats\": { \"concepts\": $TEST_POSITION_COUNT } }," >> "$OUTPUT_FILE"
echo "        \"Transaction\": { \"type\": \"domain\", \"stats\": { \"concepts\": $TEST_TRANSACTION_COUNT } }," >> "$OUTPUT_FILE"
echo "        \"Payment\": { \"type\": \"domain\", \"stats\": { \"concepts\": $TEST_PAYMENT_COUNT } }" >> "$OUTPUT_FILE"
echo '      }' >> "$OUTPUT_FILE"
echo '    }' >> "$OUTPUT_FILE"
echo '  },' >> "$OUTPUT_FILE"
echo '  "crossDomain": {}' >> "$OUTPUT_FILE"
echo '};' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Empty RBCZ placeholders (required by app but empty)
echo "// RBCZ domains (empty - public version)" >> "$OUTPUT_FILE"
echo 'const INVESTMENT_DATA = { "domain": { "name": "Investment", "path": "RBCZ:MIB:Investment" }, "concepts": [], "categorizations": [], "relationships": [] };' >> "$OUTPUT_FILE"
echo 'const PAYMENTS_DATA = { "domain": { "name": "Payments", "path": "RBCZ:MIB:Payments" }, "concepts": [], "categorizations": [], "relationships": [] };' >> "$OUTPUT_FILE"
echo 'const RETAIL_DATA = { "domain": { "name": "Retail", "path": "RBCZ:Retail" }, "concepts": [], "categorizations": [], "relationships": [] };' >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Test Order data
echo "// Test Order domain" >> "$OUTPUT_FILE"
echo -n "const TEST_ORDER_DATA = " >> "$OUTPUT_FILE"
if [ -f "$TEST_ORDER_FILE" ]; then
    cat "$TEST_ORDER_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Test/Order: $TEST_ORDER_COUNT concepts"
else
    echo '{ "domain": { "name": "Order", "path": "Test:Order" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Test/Order: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Test Position data
echo "// Test Position domain" >> "$OUTPUT_FILE"
echo -n "const TEST_POSITION_DATA = " >> "$OUTPUT_FILE"
if [ -f "$TEST_POSITION_FILE" ]; then
    cat "$TEST_POSITION_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Test/Position: $TEST_POSITION_COUNT concepts"
else
    echo '{ "domain": { "name": "Position", "path": "Test:Position" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Test/Position: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Test Transaction data
echo "// Test Transaction domain" >> "$OUTPUT_FILE"
echo -n "const TEST_TRANSACTION_DATA = " >> "$OUTPUT_FILE"
if [ -f "$TEST_TRANSACTION_FILE" ]; then
    cat "$TEST_TRANSACTION_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Test/Transaction: $TEST_TRANSACTION_COUNT concepts"
else
    echo '{ "domain": { "name": "Transaction", "path": "Test:Transaction" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Test/Transaction: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Test Payment data
echo "// Test Payment domain" >> "$OUTPUT_FILE"
echo -n "const TEST_PAYMENT_DATA = " >> "$OUTPUT_FILE"
if [ -f "$TEST_PAYMENT_FILE" ]; then
    cat "$TEST_PAYMENT_FILE" >> "$OUTPUT_FILE"
    echo "  ✅ Test/Payment: $TEST_PAYMENT_COUNT concepts"
else
    echo '{ "domain": { "name": "Payment", "path": "Test:Payment" }, "concepts": [] }' >> "$OUTPUT_FILE"
    echo "  ⚠️  Test/Payment: not found"
fi
echo ";" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Export
echo "// Export for application" >> "$OUTPUT_FILE"
echo "window.BKB_DATA = {" >> "$OUTPUT_FILE"
echo "  domains: DOMAINS_DATA," >> "$OUTPUT_FILE"
echo "  investment: INVESTMENT_DATA," >> "$OUTPUT_FILE"
echo "  payments: PAYMENTS_DATA," >> "$OUTPUT_FILE"
echo "  retail: RETAIL_DATA," >> "$OUTPUT_FILE"
echo "  order: TEST_ORDER_DATA," >> "$OUTPUT_FILE"
echo "  position: TEST_POSITION_DATA," >> "$OUTPUT_FILE"
echo "  transaction: TEST_TRANSACTION_DATA," >> "$OUTPUT_FILE"
echo "  payment: TEST_PAYMENT_DATA" >> "$OUTPUT_FILE"
echo "};" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "console.log('✅ BKB data loaded (PUBLIC - Test only):', Object.keys(window.BKB_DATA));" >> "$OUTPUT_FILE"

# Report
FILE_SIZE=$(wc -c < "$OUTPUT_FILE" | tr -d ' ')
FILE_SIZE_KB=$((FILE_SIZE / 1024))
echo ""
echo "✅ Generated $OUTPUT_FILE (PUBLIC VERSION)"
echo "   Size: ${FILE_SIZE_KB} KB"
echo "   Contains: Test data only (Order, Position, Transaction, Payment)"
echo "   RBCZ data: NOT INCLUDED"
echo ""
echo "🔓 Safe for public GitHub repository!"
