# Domain: Position
# Path: Test:Position
# Generated by ontology-lift with FIBO enrichment
# FIBO Coverage: 100.0%

# Concepts
Account: container for records associated with a business arrangement for regular transactions and services
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/ClientsAndAccounts/Account
  # Match: exact (confidence: 1.00)
  # Extends: account
Bond position: position in some fund, which may be defined in terms of fund units
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/SEC/Funds/Funds/FundPosition
  # Match: fuzzy (confidence: 0.85)
  # Extends: fund position
Cash position: investor's stake, i.e., a holding, in a particular asset (such as an individual security)
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Position
  # Match: keyword (confidence: 0.84)
  # Extends: position
Closed position: investor's stake, i.e., a holding, in a particular asset (such as an individual security)
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Position
  # Match: keyword (confidence: 0.84)
  # Extends: position
Custody fee: A contract between an investor and a custodian bank for the safekeeping of securities and other assets.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesHoldings/CustodyAgreement
  # Match: keyword (confidence: 0.73)
  # Extends: Custody Agreement
Equity position: position in an equity instrument
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/SEC/Equities/EquityInstruments/EquityPosition
  # Match: exact (confidence: 1.00)
  # Extends: equity position
Fund position: position in some fund, which may be defined in terms of fund units
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/SEC/Funds/Funds/FundPosition
  # Match: exact (confidence: 1.00)
  # Extends: fund position
Long position: investor's stake, i.e., a holding, in a particular asset (such as an individual security)
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Position
  # Match: keyword (confidence: 0.84)
  # Extends: position
Market value: price an asset would sell for in the market
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FND/Arrangements/Assessments/MarketValue
  # Match: exact (confidence: 1.00)
  # Extends: market value
Open position: investor's stake, i.e., a holding, in a particular asset (such as an individual security)
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Position
  # Match: keyword (confidence: 0.84)
  # Extends: position
Order: An instruction from a customer or client to buy or sell securities, commodities, or other financial instruments.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Order
  # Match: exact (confidence: 1.00)
  # Extends: Order
Position: investor's stake, i.e., a holding, in a particular asset (such as an individual security)
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Position
  # Match: exact (confidence: 1.00)
  # Extends: position
Securities position: A holding of a security or commodity, either long or short, by an investor or trader.
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/SEC/Securities/SecuritiesHoldings/Position
  # Match: synonym (confidence: 0.90)
  # Extends: Position
Short position: investor's stake, i.e., a holding, in a particular asset (such as an individual security)
  # Source: FIBO (confidence: MAPPED)
  # FIBO: https://spec.edmcouncil.org/fibo/ontology/FBC/ProductsAndServices/FinancialProductsAndServices/Position
  # Match: keyword (confidence: 0.84)
  # Extends: position

# Categorizations
Position =< @ by asset type >= [Cash position, Securities position]
Position =< @ by direction >= [Long position, Short position]
Position =< @ by state >= [Open position, Closed position]
Securities position =< @ by instrument >= [Equity position, Bond position, Fund position]
